name: Deploy to a Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Build Docker image
      run: |
        docker build -t fastapiapp:latest .

    - name: Save Docker image as tar archive
      run: |
        docker save -o image.tar fastapiapp:latest

    - name: Change file permissions
      run: chmod a+r image.tar

    - name: Check if image.tar exists
      run: ls -lah image.tar
    
    - name: Copy Docker image to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: "image.tar"
        target: "/home/${{ secrets.VM_USERNAME }}/image.tar"

    - name: Load Docker image on Azure VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo bash stop.sh
          sudo docker load -i /home/${{ secrets.VM_USERNAME }}/image.tar/image.tar
          sudo docker run -d -p 8000:8000 fastapiapp:latest
          sudo systemctl start nginx
          sudo systemctl reload nginx
          rm -rf image.tar
